# Generated by Django 2.2.6 on 2019-10-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descricao', models.CharField(max_length=50)),
                ('preco', models.IntegerField()),
            ],
        ),
    ]
